### ISSUE TITLE
无法下载扩展

### ISSUE THREAD

**Issue by RancherJie** [nonameShijian/noname-shijian-android#10]
![Screenshot_20241208_143123](https://github.com/user-attachments/assets/7a5dd413-dea6-4e50-8214-298be56daf84)
无名杀版本1.10.16
本扩展仓库地址为 https://gitee.com/RancherJie/noname_xingbei_extension/raw/master/
该地址在win客户端启动的无名杀（同版本）中可以正常下载并安装扩展。
![Screenshot_20241208_144432](https://github.com/user-attachments/assets/89916d64-ebfc-432e-8d2c-b6125e523df7)
其他仓库也会有类似问题

**Comment by nonameShijian** [comment]
这个问题应该去libccy/noname里提issue

**Comment by nonameShijian** [comment]
哦你说app是吧，最新的应该解决了忘掉的跨域配置来着

**Comment by RancherJie** [comment]
> 哦你说app是吧，最新的应该解决了忘掉的跨域配置来着

诗笺和尤里的都试了，都存在这个问题。都是截止回复时的最新版。目前已经在libccy/noanme里提了，当时就吧这个issues关了

**Comment by nonameShijian** [comment]
我测试一下是可用的

![Screenshot_2024-12-13-18-21-18-611_com.noname.shijian.jpg](https://github.com/user-attachments/assets/d5cf4267-8e4c-4935-9140-33bf331c2dc1)

![Screenshot_2024-12-13-18-21-26-023_com.noname.shijian.jpg](https://github.com/user-attachments/assets/a0d378ec-feae-4d9f-a8e5-45a6eb31e1e8)

**Comment by nonameShijian** [comment]
我看一下下载功能
