### ISSUE TITLE
本人制作懒人包，请求授权

### ISSUE THREAD

**Issue by RancherJie** [nonameShijian/noname-shijian-android#7]
本人基于[libccy/noname](https://github.com/libccy/noname)制作桌游星杯传说[RancherJie/noname_xingbei](https://github.com/RancherJie/noname_xingbei)
现欲制作懒人包用于分发，将会贴出本项目地址 https://github.com/nonameShijian/noname-shijian-android

**Comment by universe-st** [comment]
没问题的。安卓源码里面有个包名检测，自己修改一下就行。主要防的是MT党。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月2日(周四) 中午11:14
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [nonameShijian/noname-shijian-android] 本人制作懒人包，请求授权 (Issue #7)




 
本人基于libccy/noname制作桌游星杯传说RancherJie/noname_xingbei
 现欲制作懒人包用于分发，将会贴出本项目地址 https://github.com/nonameShijian/noname-shijian-android

**Comment by RancherJie** [comment]
好的，谢谢

**Comment by RancherJie** [comment]
你好，我想咨询具体如何制作懒人包，本人没接触过安卓开发。之前因更新内容，没有尝试制作懒人包，最近内容要更新完毕了，尝试制作，发现不知道如何制作。

**Comment by nonameShijian** [comment]
你看readme做一下

**Comment by RancherJie** [comment]
readme里内容做了

**Comment by nonameShijian** [comment]
那你做到哪了

**Comment by RancherJie** [comment]
打开Android Studio了

**Comment by RancherJie** [comment]
![image](https://github.com/user-attachments/assets/556e7caa-ca3b-47c1-852a-32bc2d3270c6)

**Comment by nonameShijian** [comment]
后面就是运行啊，不会的话可以百度，自己创建项目后，把本项目的除了“platform”目录的其他文件夹复制到你项目里然后生成安卓平台的代码去运行

你要是想改包名的话，创建项目时候就改了，以及把mainactivity里的        CheckUtils.check(this, Executors.newFixedThreadPool(5));这句删了

**Comment by RancherJie** [comment]
运行打包代码，提示缺少文件。我尝试创建个新项目进行打包

**Comment by RancherJie** [comment]
通过新建项目，再把文件复制到项目目录的方式可以打包，但打包结果明显不对，是一个5M的apk文件；尝试调试，测试机显示“Hello World”

**Comment by nonameShijian** [comment]
你应该去学一下cordova项目的web文件怎么修改

**Comment by RancherJie** [comment]
直接对仓库原文件进行打包也不行
![image](https://github.com/user-attachments/assets/9ac4a3b8-a88a-495b-a88a-4dc2c3ad36e9)

**Comment by nonameShijian** [comment]
打包apk是android studio里打包的，不是通过命令行

**Comment by RancherJie** [comment]
![image](https://github.com/user-attachments/assets/4604f164-c4b9-4937-9f64-a7d098518625)

**Comment by nonameShijian** [comment]
androidstudio打开的是platform/android目录，不是根目录

**Comment by RancherJie** [comment]
![image](https://github.com/user-attachments/assets/be7075db-361c-490b-94d2-8d3dd67e8ef2)

**Comment by nonameShijian** [comment]
那不太清楚了，可能因为安全限制这个文件没上传吧

**Comment by nonameShijian** [comment]
还是建议你在我的这个项目基础上，把platform/android文件夹通过cordova命令删了然后重新添加安卓平台看看

**Comment by RancherJie** [comment]
好的，我试试

**Comment by RancherJie** [comment]
目前已经可以build了，但无法使用或者解压内置的压缩包，软件有检测到内置压缩包；目前通过下载可以启动。
由于不支持旧版本的部分库，这些库我都替换为了androidx的库
我还删除了重复的 <uses-permission> 声明，位于platforms\android\app\src\main\AndroidManifest.xml
 uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" /

目前在未有游戏本体文件下启动，都会报如下错误
![屏幕截图 2024-08-12 103933](https://github.com/user-attachments/assets/eed6acbe-9a60-41ca-aed4-891452a92f5b)

**Comment by RancherJie** [comment]
if (confirm('检测到内置压缩包存在，是否解压？\n注意: 此客户端不是懒人包的情况建议点击取消，然后在此页面在线下载最新离线包')) cordova.exec(() => { }, () => { }, 'FinishImport', 'assetZip', []);
经尝试，该段位于index.js的代码，cordova.exec(() => { }, () => { }, 'FinishImport', 'assetZip', []); 未失败执行了
