### ISSUE TITLE
全能搜索功能请求

### ISSUE THREAD

**Issue by duzhilong** [nonameShijian/noname-shijian-android#8]
能否在全能搜索的搜索界面中加入可以复制武将id的功能。
![image](https://github.com/user-attachments/assets/40cd012e-acd1-4565-981d-27b3dfef5661)

**Comment by nonameShijian** [comment]
有没有可能你双击前面的中文就可以复制了

**Comment by duzhilong** [comment]
> 有没有可能你双击前面的中文就可以复制了

技能可以这样，武将名id不可以啊

**Comment by nonameShijian** [comment]
前面蓝色的

**Comment by duzhilong** [comment]
可以，感谢哥
